[package]
name = "swc_plugin_react_slot"
authors = ["Bernardo Sunderhus <bernardo.sunderhus@gmail.com>"]
description = "SWC plugin for removing indentation of template literal"
edition = "2021"
license = "MIT"
publish = false
version = "0.1.0"
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
strip = "symbols"

[dependencies]
serde = "1.0.186"
serde_json = "1.0.79"
swc_core = { version = "0.90.6", features = [
  "ecma_plugin_transform",
  "common",
] }
tracing = { version = "0.1.37", features = ["release_max_level_info"] }

[dev-dependencies]
testing = "0.33.21"
tracing-test = "0.2.4"
swc_ecma_parser = "0.143.3"
